version: "3.8"

services:
  web:
    build: .
    ports:
      - "5001:80"
    depends_on:
      - db

  db:
    build: ./db/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: animalerie
      MYSQL_USER: user
      MYSQL_PASSWORD: password